name: Generate Snake Game from GitHub Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *"  # runs at midnight every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3  # Mise à jour vers v3

      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v3.1.0  # Assurez-vous d'utiliser la dernière version
        with:
          github_user_name: Sebdev43
          outputs: |
            dist/snake-dark.svg?palette=github-dark
            dist/snake-light.svg?palette=github-light

      - name: Add & Commit
        run: |
          git config --local user.email "sebdev43c@gmail.com"
          git config --local user.name "Sebdev43"
          git add dist/snake-dark.svg dist/snake-light.svg
          git commit -m "Generated snake animation"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.snake_token }}
          branch: main  # Change this to your repository's default branch if different
