name: Generate snake game

on:
  schedule: 
    - cron: "0 */12 * * *"  # Exécute toutes les 12 heures
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Generate the snake game
      - name: Generate Snake Game
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Commit and push changes
      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generated snake animation"
          branch: output
          file_pattern: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_SNAKE }}
