name: Generate Snake Game from GitHub Contributions

on:
  schedule:
    - cron: "0 0 * * *"  # Exécute tous les jours à minuit
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: generate-snake-game-from-github-contribution-grid
        uses: Sutil/snk@v01.00.02
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake2.svg
          snake_color: 'blue'

      - name: Push changes
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.SNAKE_TOKEN }}
