name: Generate Snake Game from GitHub Contributions

on:
  schedule:
    - cron: "0 0 * * *"  # Exécute tous les jours à minuit
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: Sebdev43
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generated snake animation"
          branch: main
          file_pattern: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.SNAKE_TOKEN }}

      - name: Push changes to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.SNAKE_TOKEN }}
