name: Generate snake game

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

permissions:
  contents: write  # Ajoutez cette ligne pour accorder les permissions d'écriture

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Snake Game from GitHub Contribution Grid
        uses: Platane/snk@v3.1.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake-dark.svg
            dist/github-snake.svg

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generated snake animation"
          branch: output
          file_pattern: dist/*
          repository: .
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: Sebdev43 <Sebdev43@users.noreply.github.com>
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_SNAKE }}
